//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int AccessoryID { get; set; }
        public int AccessoryType { get; set; }
        public decimal AccessoryPrice { get; set; }
        public Nullable<int> AccessoriesSold { get; set; }
        public Nullable<int> ColorID { get; set; }
        public string AccessoryDesrcp { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public string AccessoryImage { get; set; }
        public Nullable<decimal> AccessorySales { get; set; }
        public Nullable<int> StockID { get; set; }
    
        public virtual AccessoryType AccessoryType1 { get; set; }
        public virtual Color Color { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
