//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime HireDate { get; set; }
        public System.DateTime BIrthdate { get; set; }
        public string Phone_ { get; set; }
        public string Email { get; set; }
        public string Emp_Street { get; set; }
        public string Adress2 { get; set; }
        public string Emp_City { get; set; }
        public string Emp_state { get; set; }
        public string Emp_zip { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
