//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speaker
    {
        public int SpeakerID { get; set; }
        public int SpeakerType { get; set; }
        public Nullable<decimal> SpeakerPrice { get; set; }
        public Nullable<int> SpkrsSold { get; set; }
        public Nullable<int> ColorID { get; set; }
        public string SpkrDescription { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public string SpeakersImage { get; set; }
        public Nullable<decimal> SpkrSales { get; set; }
        public Nullable<int> StockID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual SpeakersType SpeakersType { get; set; }
    }
}
